name: Python CI

on:
  pull_request:
    branches:
      - master  # Trigger on PRs targeting the `master` branch

jobs:
  build:
    runs-on: ubuntu-latest  # Can also use macos-latest or windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        conda-version: '24.9.1'  # Use a specific version of Conda
        python-version: '3.12'    # Python version
        auto-activate-base: false # Prevent activation of base Conda environment
        channel-priority: false

    - name: Create Conda environment from environment.yml
      run: |
        conda env create -f environment.yml

    - name: Activate Conda environment
      run: |
        source activate Housing_price

    - name: Run tests
      run: |
        pytest

    - name: Block PR if tests fail
      if: ${{ failure() }}
      run: echo "The build failed. Please check the logs for errors." && exit 1
