name: Python CI

on:
  pull_request:
    branches:
      - master  # Trigger on PRs targeting the `master` branch

jobs:
  build:
    runs-on: ubuntu-latest  # Can also use macos-latest or windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: add conda to PATH
      run: echo "##vso[task.prependpath]$CONDA/bin"

    - name: Create Conda environment from environment.yml and activate it
      run: |
        conda env create -f environment.yml
        source $CONDA/bin/activate Housing_pricing

    - name: Activate the conda env
      run: |
        source $CONDA/bin/activate Housing_pricing

    - name: Run tests
      run: |
        conda install pytest --yes
        source pytest

    - name: Block PR if tests fail
      if: ${{ failure() }}
      run: echo "The build failed. Please check the logs for errors." && exit 1
